### ISSUE TITLE
Remove unwanted files from Press page

### ISSUE THREAD

**Issue by striebwj** [ClassicPress/ClassicPress-docs#5]
On the [Press and Branding](https://docs.classicpress.net/press-and-branding/) page there are 3 unwanted files:
- README.md
- autogenerated
- bin

It would probably make sense to tweak the `generate-assets.sh` from the [ClassicPress-Design](https://github.com/ClassicPress/ClassicPress-Design) to include a copy of the svgs.

**Comment by nylen** [comment]
This should be done by modifying the code [here](https://github.com/ClassicPress/site-docs/blob/master/wp-content/mu-plugins/file-list.php) to implement the mockup posted [on the forums](https://forums.classicpress.net/t/where-can-i-download-the-logos-and-assets/1807/5), and at the same time also moving these widgets to the main [brand guidelines page](https://www.classicpress.net/brand-guidelines/) and removing this page from the docs site.

I'm planning to tackle this next week.

**Comment by nylen** [comment]
This is done:

- https://github.com/ClassicPress/site-www/commit/f48304d9f9ea5e9cf677172f20ea6d6191c206ac and https://github.com/ClassicPress/site-www/commit/935e049d85e68f534a6c5494f73eea35d2c659f6
- https://github.com/ClassicPress/site-docs/compare/9a9042d...3a787f6
- https://github.com/ClassicPress/ClassicPress-docs/commit/a0847eb77f0a0240f466f9f6f2b0d1e1f7503649
- https://github.com/ClassicPress/ClassicPress-Design/compare/2b5f1cb...4fb92b2
- Content edits at https://www.classicpress.net/brand-guidelines/
